import type { Metadata } from "next";
import localFont from "next/font/local";
import {} from 'next/font/google'
import "./globals.css";
import logo from '/untitled.webp'
import Provider from "./provider";
import { WebSocketProvider } from "../Context/wsContext";
import { Suspense } from "react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Musi",
  icons:{
    icon:'/untitled.webp'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Provider>
          <WebSocketProvider>
            <Suspense fallback={<div>Loading...</div>}>
              {children}
            </Suspense>
          </WebSocketProvider>
        
        </Provider>
        
      </body>
    </html>
  );
}
